# -*- coding: utf-8 -*-
"""individualModulo4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4Rex2OvpnB9IbPTc2khwN16QNipsbBk

TRABALHO INDIVIDUAL MÓDULO 4 (THIAGO BERNARDES CHECHIA)

- IMPORTANDO AS BIBLIOTECAS NECESSÁRIAS
"""

import pandas as pd
import numpy as np

"""- IMPORTANDO O RELATÓRIO EM FORMATO .csv  (comma separated values)(valores separados por vírgulas)"""

url = 'https://drive.google.com/uc?export=download&id=1wji-DooPqQ3RzCotMFoszmjzFSakf0zH'
relatorio = pd.read_csv(url)
relatorio

"""- Criando o mesmo relatório sem a necessidade de importa-lo"""

dados = {'Dia': ['Segunda','Terca','Quarta','Quinta','Sexta','Sábado','Domingo'],
'Horas Trabalhadas': [6,7,8,6,7,5,4],'Bugs Corrigidos':[3,2,1,4,3,2,1], 'Tarefas Concluídas':[5,4,6,4,5,3,2]}

relatorio1 = pd.DataFrame(dados, index = [0,1,2,3,4,5,6])
relatorio1

"""- TOTAL DE HORAS TRABALHADAS"""

relatorio1[:7]['Horas Trabalhadas'].sum()

"""- MÉDIA DIÁRIA DE HORAS TRABALHADAS"""

relatorio1[:7]['Horas Trabalhadas'].median()

"""- TOTAL DE BUGS CORRIGIDOS"""

relatorio1[:7]['Bugs Corrigidos'].sum()

"""- MÉDIA DIÁRIA DE BUGS CORRIGIDOS"""

relatorio1[:7]['Bugs Corrigidos'].median()

"""- TOTAL DE TAREFAS CONCLUÍDAS"""

relatorio1[:7]['Tarefas Concluídas'].sum()

"""- MÉDIA DIÁRIA DE TAREFAS CONCLUÍDAS"""

relatorio1[:7]['Tarefas Concluídas'].median()

"""- PRODUTIVIDADE DIÁRIA  ( TAREFAS CONCLUÍDAS POR HORA )"""

ProdutividadeDiaria = relatorio1[:7]['Horas Trabalhadas'].sum() / relatorio1[:7]['Tarefas Concluídas'].sum()
ProdutividadeDiaria

"""- APRESENTANDO A PRODUTIVIDADE DIÁRIA COM NÚMERO ARREDONDADO"""

numero = ProdutividadeDiaria
numero_arredondado = round(numero, 2)
numero_arredondado

s1 = pd.Series([43,6,16,2,29,4,1.48], index = ['Total de Horas Trabalhadas','Média de horas trabalhadas','Total de Bugs Corrigidos','Média diária de Bugs Corrigidos','Total de Tarefas Concluídas','Média diária de Tarefas Concluídas','Produtividade Diária'])
s1