# -*- coding: utf-8 -*-
"""projetoIndividualModulo4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4Rex2OvpnB9IbPTc2khwN16QNipsbBk

TRABALHO INDIVIDUAL MÓDULO 4 (THIAGO BERNARDES CHECHIA)

- IMPORTANDO AS BIBLIOTECAS NECESSÁRIAS
"""

import pandas as pd
import numpy as np

"""- IMPORTANDO O RELATÓRIO EM FORMATO .csv  (comma separated values)(valores separados por vírgulas)"""

url = 'https://drive.google.com/uc?export=download&id=1wji-DooPqQ3RzCotMFoszmjzFSakf0zH'
relatorio = pd.read_csv(url)
relatorio

"""- Criando o mesmo relatório sem a necessidade de importa-lo"""

dados = {'Dia': ['Segunda','Terca','Quarta','Quinta','Sexta','Sábado','Domingo'],
'Horas Trabalhadas': [6,7,8,6,7,5,4],'Bugs Corrigidos':[3,2,1,4,3,2,1], 'Tarefas Concluídas':[5,4,6,4,5,3,2]}

relatorio1 = pd.DataFrame(dados, index = [0,1,2,3,4,5,6])
relatorio1

"""- TOTAL DE HORAS TRABALHADAS"""

relatorio1[:7]['Horas Trabalhadas'].sum()# este comando soma todas as horas trabalhadas

"""- MÉDIA DIÁRIA DE HORAS TRABALHADAS"""

relatorio1[:7]['Horas Trabalhadas'].mean()#este comando faz a media de horas trabalhadas
print('{:.2f}'.format(relatorio1[:7]['Horas Trabalhadas'].mean()))# este comando forca a exibicao de um numero com duas casas decimais

"""- TOTAL DE BUGS CORRIGIDOS"""

relatorio1[:7]['Bugs Corrigidos'].sum()#este comando Soma todas as tarefas

"""- MÉDIA DIÁRIA DE BUGS CORRIGIDOS"""

relatorio1[:7]['Bugs Corrigidos'].mean()# este comando faz a media dos bugs corrigidos
print('{:.2f}'.format(relatorio1[:7]['Bugs Corrigidos'].mean()))# este comando forca a exibicao de um numero com duas casas decimais

"""- TOTAL DE TAREFAS CONCLUÍDAS"""

relatorio1[:7]['Tarefas Concluídas'].sum()#este comando soma todas as tarefas concluidas

"""- MÉDIA DIÁRIA DE TAREFAS CONCLUÍDAS"""

relatorio1[:7]['Tarefas Concluídas'].mean()#utilizado comando mean para fazer a media das tarefas concluidas.
print('{:.2f}'.format(relatorio1[:7]['Tarefas Concluídas'].mean()))# este comando forca a exibicao de um numero com duas casas decimais

"""- PRODUTIVIDADE DIÁRIA  ( TAREFAS CONCLUÍDAS POR HORA )"""

ProdutividadeDiaria = relatorio1[:7]['Horas Trabalhadas'].sum() / relatorio1[:7]['Tarefas Concluídas'].sum()#este comando soma as horas trabalhadas
print('{:.2f}'.format(relatorio1[:7]['Horas Trabalhadas'].sum() / relatorio1[:7]['Tarefas Concluídas'].sum()))#forcando a exibicao do print formatando o numero obtido resultado da divisao de total de tarefas concluidas pelo total de horas trabalhadas.

"""- APRESENTANDO A PRODUTIVIDADE DIÁRIA COM NÚMERO ARREDONDADO"""

numero = ProdutividadeDiaria# criada a variavel numero definida resultante da variavel ProdutividadeDiaria definida acima
numero_arredondado = round(numero, 2)# este numero arredonda o resultado com comando round
numero_arredondado# este chama o numero arredonda definido acima

"""- CRIACAO DE UMA SERIES PARA APRESENTAR OS RESULTADOS DE FORMA ORGANIZADA"""

s1 = pd.Series([43,6.14,16,2.29,29,4.14,1.48], index = ['Total de Horas Trabalhadas','Média de horas trabalhadas','Total de Bugs Corrigidos','Média diária de Bugs Corrigidos','Total de Tarefas Concluídas','Média diária de Tarefas Concluídas','Produtividade Diária'])
s1# os index sao definidos acima e seus respectivos valores sao definidos na Series acima